spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123456
    url: jdbc:mysql://localhost:3306/tbqr?useUnicode=true&serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8
imgurl:
  path: /opt/app/tbqr/imgs/
